diode graph
waterloo-rocketry/Payload-2020-Analysis pull request #1
Opened 2020-10-02 00:48 UTC by PCModeActivate

Diode Graph Generator V1.0

2020-10-02 23:06 UTC, jacobdeery reviewed
Cool, thanks for the script! The code looks fine, mostly just formatting comments

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-:-MIfZ3lpEyzdc2czIds1:blj5hqq)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @jacobdeery, @LanaTomlin, @PCModeActivate, and @wendi-yu)

___
*[Diode_Graph.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfWciN4b7eQrLaWkx_:-MIfWciO9rAAvd3yaXZa:bck3ywb) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L3)):*
> ```
> import plotly.express as py
> ```
The usual alias for plotly.express is `px` (`py` is usually short for "Python")
___
*[Diode_Graph.py, line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfWQEO2YnWbmcSH4aX:-MIfWQEO2YnWbmcSH4aY:bwojxfe) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L5)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> import numpy as np
> import csv
> import plotly.express as py
> import pandas as pd
> import datetime
> ```
</details>


Conventionally, imports are sorted in this order:

```
standard library

third party

local
```

with each block separated by a newline. For this repo, that would mean:
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
import csv
import datetime

import numpy as np
import plotly.express as px
import pandas as pd
> ```
</details>

___
*[Diode_Graph.py, line 11 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYq3M2d2qS51oqSLW:-MIfYq3M2d2qS51oqSLX:b-xsxkam) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L11)):*
> ```
> if(row[0] == "testStarted"):
> ```
Usually in Python we'd just write it like this: `if row[0] == "testStarted":`
___
*[Diode_Graph.py, line 13 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYo3SCgAadENGTK5n:-MIfYo3SCgAadENGTK5o:byqq1yn) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L13)):*
> ```
> #do something idk what yet
> ```
___
*[Diode_Graph.py, line 14 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfWyegBJRP1L_940WK:-MIfWyegBJRP1L_940WL:b1t38af) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L14)):*
> ```
> else:················
> ```
Remove the trailing whitespace on this line
___
*[Diode_Graph.py, line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYMEb1N-oRF1veSoH:-MIfYMEb1N-oRF1veSoI:b-92dzet) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L18)):*
> ```
>             min = int(t/59000000)
>             sec = int((t-(59000000*min))/999999)
>             mic = int ((t-(59000000*min)-(999999*sec)))
> ```
hmm, I'm not sure I understand exactly what's happening here. What's the significance of `59000000`? Typically for "magic numbers" it's nice to put them in a named variable so that your code is more self-documenting.
___
*[Diode_Graph.py, line 28 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfX0HBD7A7Yx3lpgE3:-MIfX0HBD7A7Yx3lpgE4:b-z2wyvy) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L28)):*
> ```
>     title="Voltage v Time",
>     xaxis_title="Time",
>     yaxis_title="Voltage"
> ```
Indent this block by one more level, since it's inside parens
___
*[Diode_Graph.py, line 28 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfZA753IiPggsmw1OM:-MIfZA753IiPggsmw1ON:b-2e3ps8) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L28)):*
> ```
> xaxis_title="Time",
>     yaxis_title="Voltage"
> ```
Add units to the labels
___
*[README.md, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfY806AKgj1MwKmheC:-MIfY806AKgj1MwKmheD:b8bppi7) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/README.md#L3)):*
> ```
> Successful generation of the graph should also require internet access, as the compiled graph should be shown in a pop-up browser window.
> ```
Actually, I don't think Internet access is required; the graph will be shown in a browser, but it's from a local web server on your machine, not one on the Internet.
___
*[README.md, line 10 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfXXKzE1xlYgsMDvqA:-MIfXXKzE1xlYgsMDvqB:bv9jurp) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/README.md#L10)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> - Python 3
> - NumPy
> - Plotly
> - Pandas
> ```
</details>

Thank you for listing the dependencies! Typically, for Python, it's nice to list them in a `requirements.txt` file - that way, you can automatically install all of them by just running `pip install -r requirements.txt`.

[Here's](https://github.com/waterloo-rocketry/topside/blob/master/requirements.txt) an example from Topside. Note that in Topside, we explicitly specify the exact versions of all of the libraries. That's probably not necessary for this script, since it's much simpler.


<!-- Sent from Reviewable.io -->

2020-10-02 23:32 UTC, wendi-yu reviewed
Yep, Jacob covered basically everything I would've said, lgtm too :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-:-MIfe3fy0uWl7WvNEbX4:bl53fh3)* status: 0 of 3 files reviewed, 12 unresolved discussions (waiting on @jacobdeery, @LanaTomlin, @PCModeActivate, and @wendi-yu)

___
*[Diode_Graph.py, line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYMEb1N-oRF1veSoH:-MIfaZJzBnWUQ86f5gja:bskda08) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L18)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             min = int(t/59000000)
>             sec = int((t-(59000000*min))/999999)
>             mic = int ((t-(59000000*min)-(999999*sec)))
> ```
hmm, I'm not sure I understand exactly what's happening here. What's the significance of `59000000`? Typically for "magic numbers" it's nice to put them in a named variable so that your code is more self-documenting.
</blockquote></details>

Is t in microseconds? fwiw you can also use the modulo `%`  operator to find second and microsecond remainders :)
___
*[Diode_Graph.py, line 23 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfdmWU9Tj2OlUOlDWD:-MIfdmWU9Tj2OlUOlDWE:b-c8sc6t) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L23)):*
> ```Python
>             timeArray.append(readTime)
>             dataArray.append(readBoard)
>     df = pd.DataFrame(dict(time=timeArray, volt=dataArray))
> ```

I don't think this stuff needs to be in the `with` block anymore, does it? Might look cleaner to take it out (so back one indent level) but I don't think it actually matters that much.
___
*[README.md, line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfd-m57VNT35HHJuse:-MIfd-m67p9HcAgWFk-2:bmr6egq) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/README.md#L5)):*
> ```Markdown
> This script in its current state takes in inputs in csv format from "DIODE1.txt" and generates a graph upon running of the python file. Successful generation of the graph should also require internet access, as the compiled graph should be shown in a pop-up browser window.
> 
> The dependencies need to be installed before the script can be ran (dated Oct.1st 2020).
> ```

ran -> run, I think?


<!-- Sent from Reviewable.io -->

2020-10-04 02:03 UTC, jacobdeery reviewed
Thanks for the changes! In general, once you've addressed a review, it's good practice to reply "Done" to each of the comments that you've addressed, just so that the reviewer knows what to look for.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-:-MIlJuz2B0z4pLHrxQKD:batciou)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @jacobdeery, @LanaTomlin, and @PCModeActivate)

___
*[Diode_Graph.py, line 13 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYo3SCgAadENGTK5n:-MIlKpc-3cXDNpZtaJ0K:b8opv5q) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L13)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> #do something idk what yet
> ```

</blockquote></details>

Can you make this comment a bit more clear? Is this functionality that we will want to add in the future?
___
*[Diode_Graph.py, line 20 at r3](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIlL1jwCFUoIQ5_zhZj:-MIlL1jwCFUoIQ5_zhZk:bitonyt) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/68181c49a4d8cc44905cf60dffa8712a4b50e1c8/Diode_Graph.py#L20)):*
> ```
> microSecondToMinute
> ```
The variable is named `microsecondToMinute` with a lowercase `s`, so this line will throw an error.


<!-- Sent from Reviewable.io -->

2020-10-04 20:27 UTC, PCModeActivate reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @jacobdeery, @LanaTomlin, and @wendi-yu)

___
*[Diode_Graph.py, line 11 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYq3M2d2qS51oqSLW:-MIpHbMT0yYpErYwfrdl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L11)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> if(row[0] == "testStarted"):
> ```
Usually in Python we'd just write it like this: `if row[0] == "testStarted":`
</blockquote></details>

Done.
___
*[Diode_Graph.py, line 13 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYo3SCgAadENGTK5n:-MIpFT2P-aAvYVMccgup:bvtn00w) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L13)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Can you make this comment a bit more clear? Is this functionality that we will want to add in the future?
</blockquote></details>

I do not know if I will need to add anything here in the future (or anything at all).
___
*[Diode_Graph.py, line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYMEb1N-oRF1veSoH:-MIpGWuC8ohPxQFB-aFT:bt2vr1b) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L18)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is t in microseconds? fwiw you can also use the modulo `%`  operator to find second and microsecond remainders :)
</blockquote></details>

Fixed.
___
*[Diode_Graph.py, line 23 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfdmWU9Tj2OlUOlDWD:-MIpG_Ca2ZOK3rxQMzL7:b-dlrtnu) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L23)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I don't think this stuff needs to be in the `with` block anymore, does it? Might look cleaner to take it out (so back one indent level) but I don't think it actually matters that much.
</blockquote></details>

Heh, I don't even know why the with block is here in the first place. :^)
___
*[Diode_Graph.py, line 20 at r3](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIlL1jwCFUoIQ5_zhZj:-MIpGRTL64qHYM3rd1of:bt2vr1b) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/68181c49a4d8cc44905cf60dffa8712a4b50e1c8/Diode_Graph.py#L20)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> microSecondToMinute
> ```
The variable is named `microsecondToMinute` with a lowercase `s`, so this line will throw an error.
</blockquote></details>

Fixed.
___
*[README.md, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfY806AKgj1MwKmheC:-MIpHLk15tyajlydxiIY:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/README.md#L3)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> Successful generation of the graph should also require internet access, as the compiled graph should be shown in a pop-up browser window.
> ```
Actually, I don't think Internet access is required; the graph will be shown in a browser, but it's from a local web server on your machine, not one on the Internet.
</blockquote></details>

Done.
___
*[README.md, line 10 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfXXKzE1xlYgsMDvqA:-MIpHMdpAPKGXbi9s0Tq:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/README.md#L10)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> - Python 3
> - NumPy
> - Plotly
> - Pandas
> ```
Thank you for listing the dependencies! Typically, for Python, it's nice to list them in a `requirements.txt` file - that way, you can automatically install all of them by just running `pip install -r requirements.txt`.

[Here's](https://github.com/waterloo-rocketry/topside/blob/master/requirements.txt) an example from Topside. Note that in Topside, we explicitly specify the exact versions of all of the libraries. That's probably not necessary for this script, since it's much simpler.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-04 20:34 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jacobdeery, @LanaTomlin, @PCModeActivate, and @wendi-yu)

___
*[Diode_Graph.py, line 13 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYo3SCgAadENGTK5n:-MIpITtW1I2yGncnhdly:bigpj1m) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L13)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

I do not know if I will need to add anything here in the future (or anything at all).
</blockquote></details>

Ok, sounds good.
___
*[requirements.txt, line 6 at r5](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIpIrpUBKNItoVjeFnz:-MIpIrpUBKNItoVjeFo-:b-qhch9u) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/6db56c895391ee89894c1252f3ccc4ed20033957/requirements.txt#L6)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> Python 3
> External Dependencies:
> - NumPy
> - Plotly
> - Pandas
> ```
</details>


A `requirements.txt` file should have a specific format so that it can automatically be parsed by tools like pip. [Here](https://github.com/waterloo-rocketry/topside/blob/master/requirements.txt) is the topside example. If you don't care about package versions, the contents of the file should be:

```
numpy
pandas
plotly
```


<!-- Sent from Reviewable.io -->

2020-10-05 16:55 UTC, LanaTomlin approved these changes
It looks pretty good to me. 
There are a couple of formatting things that would be nice to change in future:
1. Either making the graph change colour or adding another trace when the .txt file reads "testStarted"
2. Making the time on the graph a bit more readable. 
3. Making it pretty in terms of fonts and such.

Alas that is for a different commit.
Thank you for writing this!

2020-10-08 16:23 UTC, jacobdeery requested changes, later dismissed
Apologies for the hard block, but the most recent commit is a bit interesting and I'd like to understand the reasoning before this gets merged. Why do we want these text files tracked in Git?

2020-10-08 16:47 UTC, LanaTomlin commented
> Apologies for the hard block, but the most recent commit is a bit interesting and I'd like to understand the reasoning before this gets merged. Why do we want these text files tracked in Git?

Oh no. What text files?

2020-11-03 21:18 UTC, jacobdeery reviewed
@lanatomlin gave your changes another review

Please rename the `DIODE TEST` files to filenames without spaces so that they're easier to work with (same with the `Photodiode Test Data` directory)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-:-MLEwIF309xbXbRwekWM:b7d0deh)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[Diode_Graph.py, line 9 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEx9ET4lhzQSK0dDdL:-MLEx9ET4lhzQSK0dDdM:b-5sw0ij) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L9)):*
> ```Python
> 
> millisecondToHour = 60*60*1000
> millisecondToMinute = 60*1000 #Conversion Factor from microsecond to minute 
> ```

Change the comments to milliseconds
___
*[Diode_Graph.py, line 11 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEwPpX23eBpg7O-7Uc:-MLEwPpX23eBpg7O-7Ud:bsrvcny) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L11)):*
> ```
> DIODE3.txt
> ```
This file doesn't exist
___
*[Diode_Graph.py, line 22 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEwkUx0teyBmAax0iX:-MLEwkUx0teyBmAax0iY:b-skghim) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L22)):*
> ```
> if count%5000000:
> ```
This is taking the remainder when dividing `count` by `5000000`, and implicitly converting it to a boolean, which will be true 99.99998% of the time (we're ignoring every 5000000th data point). What is the intent of this?
___
*[Diode_Graph.py, line 23 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEx4TjDCzXEBxs2qqN:-MLEx4TjDCzXEBxs2qqO:b-rf6fgh) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L23)):*
> ```
> 1.13
> ```
Please extract as a named variable
___
*[Diode_Graph.py, line 26 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExHWI4to3hJ9IMmfu:-MLExHWI4to3hJ9IMmfv:b-lqae0r) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L26)):*
> ```
> min = int(t%millisecondToHour/millisecondToMinute)
> ```
Reusing `min` is renaming a built-in Python function, which is probably not what we want. Use `minute` instead.
___
*[Diode_Graph.py, line 33 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExuS91stQp48hezzF:-MLExuS91stQp48hezzG:b-m1q0ng) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L33)):*
> ```Python
>                     timeArray.append(readTime)
>                     dataArray.append(readBoard)
>             else:
> ```

I'm not really sure what's going on here - we want to display a figure every 5000000 loop iterations?
___
*[Diode_Graph.py, line 46 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEyBr7AX67YiFXfQjL:-MLEyBr7AX67YiFXfQjM:bhzqelz) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L46)):*
> ```Python
> 
> df = pd.DataFrame(dict(time=timeArray, volt=dataArray))
> fig = px.scatter(df, x=timeArray, y=dataArray)
> ```

When I try to run this script, I get an error on this line:

```
Traceback (most recent call last):
  File "Diode_Graph.py", line 46, in <module>
    fig = px.scatter(df, x=timeArray, y=dataArray)
  File "D:\Applications\Python38\lib\site-packages\plotly\express\_chart_types.py", line 64, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "D:\Applications\Python38\lib\site-packages\plotly\express\_core.py", line 1826, in make_figure
    args = build_dataframe(args, constructor)
  File "D:\Applications\Python38\lib\site-packages\plotly\express\_core.py", line 1280, in build_dataframe
    raise ValueError(
ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.
```

Does this script work for you?


<!-- Sent from Reviewable.io -->

2020-11-03 23:30 UTC, PCModeActivate reviewed
Welp, I don't even know what's happening here anymore. Please comment and explain if conditionals such as `count%5000000` or `float(row[1]) > 1.13` or just in general anything not intuitively explained.
Also, I believe "Diode_Graph.py" should be a generalized file at least for .csv files in the same format and same type of data as that of "Diode1.txt", so we should be avoiding inserting input-specific content in "Diode_Graph.py". Either run a modified script locally or create a new file for that matter.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-:-MLFOaJm6EfsOz6-CLcR:b-idk325)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @jacobdeery and @PCModeActivate)

___
*[Diode_Graph.py, line 26 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExHWI4to3hJ9IMmfu:-MLFNjX7ACTjMfwnynEa:bqk6xp) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L26)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> min = int(t%millisecondToHour/millisecondToMinute)
> ```
Reusing `min` is renaming a built-in Python function, which is probably not what we want. Use `minute` instead.
</blockquote></details>

Well, it may be an existing function name, but min declared as a variable is still valid (albeit probably bad in terms of convention). However, `minute` is a data type that cannot be overwritten and will break the code. So I suggest using something like `minutes` instead.
___
*[Diode_Graph.py, line 46 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEyBr7AX67YiFXfQjL:-MLFOHA7Es66xCPtEgor:bkatvxu) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L46)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

When I try to run this script, I get an error on this line:

```
Traceback (most recent call last):
  File "Diode_Graph.py", line 46, in <module>
    fig = px.scatter(df, x=timeArray, y=dataArray)
  File "D:\Applications\Python38\lib\site-packages\plotly\express\_chart_types.py", line 64, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "D:\Applications\Python38\lib\site-packages\plotly\express\_core.py", line 1826, in make_figure
    args = build_dataframe(args, constructor)
  File "D:\Applications\Python38\lib\site-packages\plotly\express\_core.py", line 1280, in build_dataframe
    raise ValueError(
ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.
```

Does this script work for you?
</blockquote></details>

I think the code is broken at the latest commit.

Also it looks like the intent here is to force generate a graph at count == 5000000, however, there is still a generate/display bloc leftover at the end of the loop after the with block. Not sure why that is, and it is referencing the arrays within the with block (causing scope errors).
___
*[requirements.txt, line 6 at r5](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIpIrpUBKNItoVjeFnz:-MLFONAj8J-O43IzLht4:bt3sk6x) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/6db56c895391ee89894c1252f3ccc4ed20033957/requirements.txt#L6)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> Python 3
> External Dependencies:
> - NumPy
> - Plotly
> - Pandas
> ```

A `requirements.txt` file should have a specific format so that it can automatically be parsed by tools like pip. [Here](https://github.com/waterloo-rocketry/topside/blob/master/requirements.txt) is the topside example. If you don't care about package versions, the contents of the file should be:

```
numpy
pandas
plotly
```
</blockquote></details>

does it need to be strictly in alphabetical order?


<!-- Sent from Reviewable.io -->

2020-11-04 01:22 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @jacobdeery and @PCModeActivate)

___
*[Diode_Graph.py, line 26 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExHWI4to3hJ9IMmfu:-MLFq4rPCpxwL-rCx2aZ:bw00f0w) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L26)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Well, it may be an existing function name, but min declared as a variable is still valid (albeit probably bad in terms of convention). However, `minute` is a data type that cannot be overwritten and will break the code. So I suggest using something like `minutes` instead.
</blockquote></details>

What problem do you see with `minute`? It works fine if I change it
___
*[requirements.txt, line 6 at r5](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIpIrpUBKNItoVjeFnz:-MLFqDIP5yCrx6vuROS-:b-2x9h14) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/6db56c895391ee89894c1252f3ccc4ed20033957/requirements.txt#L6)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

does it need to be strictly in alphabetical order?
</blockquote></details>

Nope; usually is by convention, but not required. FYI it's just `numpy` (all lowercase, no capital P)


<!-- Sent from Reviewable.io -->

2020-11-06 00:53 UTC, LanaTomlin commented
So none of those changes were supposed to be in the commit that was a mistake - those were me playing around with data.

2020-11-23 05:04 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: 0 of 11 files reviewed, 11 unresolved discussions (waiting on @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[Diode_Graph.py, line 23 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfdmWU9Tj2OlUOlDWD:-MMnSUOY-1Oq96hCvxq-:bpn64i2) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L23)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Heh, I don't even know why the with block is here in the first place. :^)
</blockquote></details>

I think the main advantage of the `with open(filepath) as filename` is that it automatically closes the file for you after you exit the block, whereas if you just manually open the file yourself you'll have to manually close it afterwards too. [Here's](https://cmdlinetips.com/2016/01/opening-a-file-in-python-using-with-statement/) an article :0
___
*[Diode_Graph.py, line 13 at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MMnTQhn-1V-OqpaSqAi:-MMnTQhn-1V-OqpaSqAj:b-4v85ia) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/Diode_Graph.py#L13)):*
> ```Python
> millisecondToMinute = 60*1000 #Conversion Factor from millisecond to minute 
> millisecondToSecond = 1000 #Conversion Factor from millisecond to second
> with open("Photodiode Test Data/{}.txt".format(filename), newline='') as csvfile:
> ```

An easier way to assemble the file name string might be with fstrings, which are like the `.format()` thing you're doing but inline. So
`with open(f"Photodiode Test Data/{filename}.txt"...`
Also, is the "Photodiode Test Data" part a folder name? If so, you might want to remove the spaces - spaces in paths tend to break things.
___
*[Diode_Graph.py, line 40 at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MMnU1ps1_k7DP4GaHIh:-MMnU1ps1_k7DP4GaHIi:b8i732p) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/Diode_Graph.py#L40)):*
> ```Python
>     yaxis_title="Volt"
> )
> fig.write_html("graph/GRAPH-{}.html".format(filename))
> ```

Final newline :0


<!-- Sent from Reviewable.io -->

2020-11-29 20:02 UTC, PCModeActivate reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-:-MNKaLVu--jZ7a-v0J6a:bnfp4nl)* status: 0 of 11 files reviewed, 11 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[Diode_Graph.py, line 9 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEx9ET4lhzQSK0dDdL:-MNKZMM6DyS7JypJ59Q3:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L9)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Change the comments to milliseconds
</blockquote></details>

Done.
___
*[Diode_Graph.py, line 11 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEwPpX23eBpg7O-7Uc:-MNKZPeSEyjzKt-YqqA5:bss4a2b) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L11)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> DIODE3.txt
> ```
This file doesn't exist
</blockquote></details>

Removed.
___
*[Diode_Graph.py, line 22 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEwkUx0teyBmAax0iX:-MNKZ5EzDI34E9ea64PY:bss4a2b) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L22)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> if count%5000000:
> ```
This is taking the remainder when dividing `count` by `5000000`, and implicitly converting it to a boolean, which will be true 99.99998% of the time (we're ignoring every 5000000th data point). What is the intent of this?
</blockquote></details>

Removed.
___
*[Diode_Graph.py, line 23 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEx4TjDCzXEBxs2qqN:-MNKZwfsEhZHMFf6RDpM:bss4a2b) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L23)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> 1.13
> ```
Please extract as a named variable
</blockquote></details>

Removed.
___
*[Diode_Graph.py, line 26 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExHWI4to3hJ9IMmfu:-MNK_3vx5ICHrVC2IIk7:bjm7nhu) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L26)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What problem do you see with `minute`? It works fine if I change it
</blockquote></details>

Like in Line 28: `Minute` is a class of data in class `Time`
But `min` still works 
___
*[Diode_Graph.py, line 33 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExuS91stQp48hezzF:-MNK_YwHC5znoWSCmkdm:bss4a2b) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L33)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I'm not really sure what's going on here - we want to display a figure every 5000000 loop iterations?
</blockquote></details>

Removed.
___
*[Diode_Graph.py, line 46 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLEyBr7AX67YiFXfQjL:-MNK__vhAAMWC5qUfpaN:b-886gsx) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L46)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

I think the code is broken at the latest commit.

Also it looks like the intent here is to force generate a graph at count == 5000000, however, there is still a generate/display bloc leftover at the end of the loop after the with block. Not sure why that is, and it is referencing the arrays within the with block (causing scope errors).
</blockquote></details>

Fixed
___
*[Diode_Graph.py, line 13 at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MMnTQhn-1V-OqpaSqAi:-MNKZfuK6jo8BCspS4ex:b3ew6sf) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/Diode_Graph.py#L13)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

An easier way to assemble the file name string might be with fstrings, which are like the `.format()` thing you're doing but inline. So
`with open(f"Photodiode Test Data/{filename}.txt"...`
Also, is the "Photodiode Test Data" part a folder name? If so, you might want to remove the spaces - spaces in paths tend to break things.
</blockquote></details>

That's usually the case, but apparently it works with whitespace here, and changing to underscore will require renaming the folder as well.
___
*[Diode_Graph.py, line 40 at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MMnU1ps1_k7DP4GaHIh:-MNKa0QUEP2sEQzHJoAR:b-w56ntt) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/Diode_Graph.py#L40)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Final newline :0
</blockquote></details>

Is a final newline needed or not needed? Im not too familiar with how the eof syntax should be.


<!-- Sent from Reviewable.io -->

2020-11-30 06:07 UTC, PCModeActivate reviewed
> Reviewed 2 of 4 files at r7, 1 of 3 files at r8, 8 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: all files reviewed, 11 unresolved discussions (waiting on @jacobdeery and @wendi-yu)



<!-- Sent from Reviewable.io -->

2021-02-02 00:28 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: all files reviewed, 6 unresolved discussions (waiting on @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[Diode_Graph.py, line 26 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExHWI4to3hJ9IMmfu:-MSV6Pje9SD_ATiHMba3:bdhwrqa) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L26)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Like in Line 28: `Minute` is a class of data in class `Time`
But `min` still works 
</blockquote></details>

I don't think that's accurate - we're not using any `Time` class here. If you're referring to the named `minute` parameter in `datetime.time`, it's perfectly fine to pass a variable that has the same name (we already do this with `hour`).
___
*[Diode_Graph.py, line 13 at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MMnTQhn-1V-OqpaSqAi:-MSV60QABnblszSRvdrE:bvrh8az) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/Diode_Graph.py#L13)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

That's usually the case, but apparently it works with whitespace here, and changing to underscore will require renaming the folder as well.
</blockquote></details>

Echoing Wendi's comment, using the f-string approach is a bit cleaner here
___
*[Diode_Graph.py, line 40 at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MMnU1ps1_k7DP4GaHIh:-MSV795K8a9y-ABfVFBt:b-9gvgco) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/Diode_Graph.py#L40)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Is a final newline needed or not needed? Im not too familiar with how the eof syntax should be.
</blockquote></details>

A final newline is desired.

You can also use f-string syntax here.
___
*[graph/diodeq-1, line 0 at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MSV7jIyEm2msnn025ok:-MSV7jIz06_ETYoP7wDh:b6vzakj) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/graph/diodeq-1#L0)):*
Hmm, I don't know if I like tracking these files in git. They're very large (nearly 100MB each!) and make it take much longer to pull from the repo.

Is there a reason that we need to track these?
___
*[requirements.txt, line 6 at r5](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIpIrpUBKNItoVjeFnz:-MSV7PmP4qCWVfOSXqcS:bmyjoyp) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/6db56c895391ee89894c1252f3ccc4ed20033957/requirements.txt#L6)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Nope; usually is by convention, but not required. FYI it's just `numpy` (all lowercase, no capital P)
</blockquote></details>

Comment on numpy still stands


<!-- Sent from Reviewable.io -->

2021-02-09 00:44 UTC, PCModeActivate reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @PCModeActivate)

___
*[Diode_Graph.py, line 26 at r7](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MLExHWI4to3hJ9IMmfu:-MT3ElEW4BD6GPNntbYG:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/4ab3f9cc4333aeacb35330c419b5126211209e70/Diode_Graph.py#L26)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I don't think that's accurate - we're not using any `Time` class here. If you're referring to the named `minute` parameter in `datetime.time`, it's perfectly fine to pass a variable that has the same name (we already do this with `hour`).
</blockquote></details>

Done.
___
*[graph/diodeq-1, line  at r9](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MSV7jIyEm2msnn025ok:-MT3EhDq4Vx2o452qcu-:bhofej8) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/fb7862cc6cfea8e7ad37bd06ceb48f6050c0cb49/graph/diodeq-1#L)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Hmm, I don't know if I like tracking these files in git. They're very large (nearly 100MB each!) and make it take much longer to pull from the repo.

Is there a reason that we need to track these?
</blockquote></details>

Deleted


<!-- Sent from Reviewable.io -->

2021-02-16 00:14 UTC, wendi-yu reviewed
One last comment from me

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-:-MTcB-JTDXxy1ksfmt0A:b-eurwta)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @PCModeActivate)

___
*[Diode_Graph.py, line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1#-MIfYMEb1N-oRF1veSoH:-MTc9NFg8vvdoeVi7L59:b-1agtkx) ([raw file](https://github.com/waterloo-rocketry/payload-2020-analysis/blob/8907d63179cce983d266839fbe775e11f6a08943/Diode_Graph.py#L18)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Nitpick for readability but I think it would be helpful to add whitespace around the `%` operators. Also maybe brackets to indicate order of operations with the multiplication?


<!-- Sent from Reviewable.io -->

2021-02-21 18:23 UTC, PCModeActivate reviewed
> Reviewed 7 of 7 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: all files reviewed, 4 unresolved discussions (waiting on @jacobdeery)



<!-- Sent from Reviewable.io -->

2021-02-26 03:29 UTC, wendi-yu approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-2020-analysis/1)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @jacobdeery, @LanaTomlin, and @PCModeActivate)



<!-- Sent from Reviewable.io -->

2021-03-02 01:12 UTC, merged